// kliktrip-premium/src/components/ui/flight-card.tsx
import * as React from "react";
import { motion } from "framer-motion";
import { ArrowRight } from "lucide-react";

import { cn } from "@/lib/utils";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

// Updated the props interface for the logo
interface FlightCardProps {
  airline: {
    name: string;
    logo: string; // Changed from React.ReactNode to string for the image URL
    flightNumber: string;
  };
  departureTime: string;
  arrivalTime: string;
  duration: string;
  stops: number;
  price: number;
  currency?: string;
  offer?: string;
  refundableType: string;
  onBook?: () => void;
  onFlightDetails?: () => void;
  className?: string;
}

// A helper for formatting currency
const formatCurrency = (amount: number, currency: string = 'INR') => {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: currency,
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
};

export const FlightCard: React.FC<FlightCardProps> = ({
  airline,
  departureTime,
  arrivalTime,
  duration,
  stops,
  price,
  currency = 'INR',
  offer,
  refundableType,
  onBook,
  onFlightDetails,
  className,
}) => {
  const stopText = stops === 0 ? "Non-stop" : `${stops} stop${stops > 1 ? "s" : ""}`;

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className={cn(
        "w-full max-w-4xl rounded-xl border bg-card text-card-foreground shadow-sm hover:shadow-md transition-shadow",
        className
      )}
    >
      <div className="p-6">
        <div className="flex justify-between items-start mb-4">
          <Badge variant="outline" className="bg-secondary/50">{refundableType}</Badge>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-12 gap-y-4 md:gap-x-6 items-center">
          {/* Airline Info */}
          <div className="md:col-span-3 flex flex-col">
            <div className="flex items-center gap-3">
              {/* Updated to use an <img> tag for the logo */}
              <div className="w-10 h-10 flex items-center justify-center rounded-md bg-muted overflow-hidden">
                <img src={airline.logo} alt={`${airline.name} logo`} className="w-full h-full object-contain" />
              </div>
              <div>
                <p className="font-semibold text-foreground">{airline.name}</p>
                <p className="text-sm text-muted-foreground">{airline.flightNumber}</p>
              </div>
            </div>
             <Button 
                variant="link" 
                className="p-0 h-auto justify-start mt-2 text-sm" 
                onClick={onFlightDetails}
                aria-label="View flight details"
            >
                Flight Details
            </Button>
          </div>

          {/* Timeline */}
          <div className="md:col-span-5 flex items-center gap-2">
            <div className="text-center">
              <p className="font-bold text-lg text-foreground">{departureTime}</p>
            </div>
            <div className="flex-grow text-center">
                <p className="text-sm text-muted-foreground">{duration}</p>
                <div className="relative w-full h-px bg-border my-1">
                    <div className="absolute top-1/2 left-0 w-full h-px flex items-center justify-center">
                       {stops > 0 && <div className="w-2 h-2 rounded-full bg-primary border-2 border-card"></div>}
                    </div>
                </div>
                <p className="text-xs font-medium text-primary">{stopText}</p>
            </div>
            <div className="text-center">
              <p className="font-bold text-lg text-foreground">{arrivalTime}</p>
            </div>
          </div>

          {/* Pricing and Booking */}
          <div className="md:col-span-4 flex flex-col md:items-end gap-2">
             <p className="text-2xl font-bold text-foreground">{formatCurrency(price, currency)}</p>
             {offer && <p className="text-sm text-green-600 dark:text-green-500 text-right">{offer}</p>}
             <Button onClick={onBook} className="w-full md:w-auto mt-2" aria-label={`Book flight for ${formatCurrency(price, currency)}`}>
                Book
                <ArrowRight className="ml-2 h-4 w-4" />
             </Button>
          </div>
        </div>
      </div>
    </motion.div>
  );
};

// kliktrip-premium/src/app/components/flight-card/flight-card.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-flight-card',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './flight-card.component.html',
  styleUrl: './flight-card.component.css'
})
export class FlightCardComponent {
  @Input() airline!: { name: string; logo: string; flightNumber: string };
  @Input() departureTime!: string;
  @Input() arrivalTime!: string;
  @Input() duration!: string;
  @Input() stops!: number;
  @Input() price!: number;
  @Input() currency = 'IDR';
  @Input() offer?: string;
  @Input() refundableType!: string;
  @Input() departureCity = 'CGK';
  @Input() arrivalCity = 'DPS';
  @Input() routeDescription = 'Jalur darat Trans Sulawesi';

  showDetails = false;

  @Output() book = new EventEmitter<void>();

  toggleDetails() {
    this.showDetails = !this.showDetails;
  }

  get stopText(): string {
    return this.stops === 0 ? 'Non-stop' : `${this.stops} stop${this.stops > 1 ? 's' : ''}`;
  }

  formatCurrency(amount: number, currency: string = 'IDR'): string {
    if (currency === 'IDR' || currency === 'Rp') {
      return new Intl.NumberFormat('id-ID', {
        style: 'currency',
        currency: 'IDR',
        minimumFractionDigits: 0,
        maximumFractionDigits: 0
      }).format(amount);
    }
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: currency,
      minimumFractionDigits: 0,
      maximumFractionDigits: 0
    }).format(amount);
  }
}

<div class="w-full max-w-4xl rounded-2xl border bg-white/95 border-slate-200/50 text-slate-800 shadow-xl hover:shadow-2xl transition-all duration-300 transform hover:-translate-y-1">
  <div class="p-6">
    <div class="flex justify-between items-start mb-4">
      <span class="inline-flex items-center rounded-full px-3 py-1 text-xs font-bold bg-blue-50 text-blue-600 uppercase tracking-wider">{{ refundableType }}</span>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-12 gap-y-4 md:gap-x-6 items-center">
      <!-- Airline Info -->
      <div class="md:col-span-3 flex flex-col">
        <div class="flex items-center gap-3">
          <div>
            <p class="font-extrabold text-slate-900 leading-tight text-base">{{ airline.name }}</p>
            <p class="text-xs font-semibold text-slate-400 mt-1">{{ airline.flightNumber }}</p>
          </div>
        </div>
        <button 
          (click)="toggleDetails()"
          class="text-blue-500 hover:underline p-0 h-auto text-left mt-3 text-xs font-bold self-start flex items-center gap-1" 
          aria-label="Detail Perjalanan">
          Detail Perjalanan
          <svg class="w-3.5 h-3.5 transition-transform duration-200" [class.rotate-180]="showDetails" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2.5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
          </svg>
        </button>
      </div>

      <!-- Timeline -->
      <div class="md:col-span-5 flex items-center gap-4 my-2 md:my-0 bg-slate-50 p-4 rounded-2xl">
        <div class="text-center min-w-[50px]">
          <p class="font-black text-xl text-slate-800 leading-none">{{ departureTime }}</p>
          <p class="text-[10px] font-bold text-slate-400 mt-1 uppercase">{{ departureCity }}</p>
        </div>
        <div class="flex-grow text-center">
          <p class="text-[10px] text-blue-500 font-bold tracking-widest uppercase mb-1">Langsung</p>
          <div class="relative w-full h-0.5 border-b-2 border-dashed border-blue-200">
            <div class="absolute -top-2 left-1/2 -translate-x-1/2 bg-slate-50 px-1 text-blue-500">
              <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M8 6v6M16 6v6M4 14h16M2 18h20M21 14V8a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v6"/>
                <circle cx="6.5" cy="18.5" r="2.5"/>
                <circle cx="17.5" cy="18.5" r="2.5"/>
              </svg>
            </div>
          </div>
          <p class="text-[10px] font-bold text-slate-400 mt-1">{{ duration }}</p>
        </div>
        <div class="text-center min-w-[50px]">
          <p class="font-black text-xl text-slate-800 leading-none">{{ arrivalTime }}</p>
          <p class="text-[10px] font-bold text-slate-400 mt-1 uppercase">{{ arrivalCity }}</p>
        </div>
      </div>

      <!-- Pricing and Booking -->
      <div class="md:col-span-4 flex flex-col md:items-end gap-1">
        <div class="text-[10px] uppercase font-bold text-slate-400 tracking-wider">Harga per pax</div>
        <p class="text-2xl font-black text-blue-600 leading-none">{{ formatCurrency(price, currency) }}</p>
        <p *ngIf="offer" class="text-xs font-semibold text-emerald-600 mt-1 text-right">{{ offer }}</p>
        <button 
          (click)="book.emit()" 
          class="w-full md:w-auto mt-3 bg-blue-500 hover:bg-blue-600 text-white font-extrabold py-2.5 px-6 rounded-full text-sm shadow-md transition-colors flex items-center justify-center gap-2" 
          [attr.aria-label]="'Pilih perjalanan untuk ' + formatCurrency(price, currency)">
          Pilih
          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2.5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3" />
          </svg>
        </button>
      </div>
    </div>

    <!-- Collapsible Details Panel -->
    <div *ngIf="showDetails" 
         class="mt-6 pt-6 border-t border-slate-100 flex flex-col gap-4 text-xs font-medium text-slate-600 bg-slate-50/50 p-4 rounded-xl"
         style="animation: slide-down 0.25s ease both">
      <div class="flex flex-col sm:flex-row sm:justify-between gap-4">
        <div>
          <span class="text-slate-400 font-bold uppercase tracking-wider block mb-1">Rute Perjalanan</span>
          <span class="text-sm font-bold text-slate-800">{{ departureCity }} → {{ arrivalCity }}</span>
        </div>
        <div>
          <span class="text-slate-400 font-bold uppercase tracking-wider block mb-1">Jenis Layanan</span>
          <span class="text-sm font-bold text-slate-800">{{ refundableType }} Class</span>
        </div>
        <div>
          <span class="text-slate-400 font-bold uppercase tracking-wider block mb-1">Estimasi Waktu</span>
          <span class="text-sm font-bold text-slate-800">{{ duration }}</span>
        </div>
      </div>
      
      <div class="border-t border-slate-200/60 pt-3">
        <span class="text-slate-400 font-bold uppercase tracking-wider block mb-1">Keterangan Rute</span>
        <p class="text-sm font-extrabold text-slate-800 mt-1">{{ routeDescription }}</p>
      </div>
    </div>
  </div>
</div>
